[package]

name = "git-bandolier"
version = "0.0.1"
description = "arm yourself up with a set of useful git commands"
readme = "README.md"
homepage = "https://crates.io/crates/git-bandolier"
license = "MIT OR Apache-2.0"
edition = "2024"
autoexamples = false
autobenches = false
default-run = "git-bandolier"

# categories = [] # https://crates.io/category_slugs

[lib]
path = "src/lib.rs"
doctest = false
bench = false

[[bin]]
name = "git-bandolier"
path = "src/main.rs"
doc = false
test = false

[[bin]]
name = "git-br"
path = "src/bin/git-br.rs"
doc = false
test = false

[[bin]]
name = "git-branches"
path = "src/bin/git-br.rs"
doc = false
test = false

[[bin]]
name = "git-list-branches"
path = "src/bin/git-br.rs"
doc = false
test = false

[[bin]]
name = "git-remotes"
path = "src/bin/git-remotes.rs"
doc = false
test = false

[[bin]]
name = "git-path"
path = "src/bin/git-path.rs"
doc = false
test = false


[[bin]]
name = "git-commit-dated"
path = "src/bin/git-commit-dated.rs"
doc = false
test = false

[[bin]]
name = "git-q"
path = "src/bin/git-q.rs"
doc = false
test = false



[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
clap = { version = "4.6.1", features = ["derive", "env", "string", "unicode", "wrap_help"] }
color-eyre = "0.6.5"
configparser = { version = "3.1.0", features = ["tokio", "indexmap"] }
env_logger = "0.11.10"
git2 = "0.20.4"
hex = "0.4.3"
iocore = { version = "3.1.0", features = ["walk-glob"] }
log = "0.4.29"
nom = "8.0.0"
sanitation = "1.0.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9.34"
thiserror = "2.0.18"
tokio = { version = "1.52.2", features = ["full"] }
toml = "1.1.2"
tracing = "0.1.44"
# block2 = "0.6.2"
# commonmark = "0.1.0"
# emacs = { version = "0.20.0", features = ["bindgen", "debug", "utf-8-validation", "nonzero-integer-conversion"] }
# hyper = "1.8.1"
# objc2 = "0.6.3"
# objc2-foundation = "0.3.2"
# objc2-user-notifications = "0.3.2"
# pest = "2.8.6"
# reqwest = { version = "0.13.2", features = ["gzip", "brotli", "blocking", "json", "multipart", "form", "query"] }
# tokio = { version = "1.49.0", features = ["full"] }
# zeromq = "0.5.0"
# chrono = { version = "0.4.44", features = ["serde"] }
# nom = "8.0.0"
# regex = "1.12.3"
# serde = { version = "1.0.228", features = ["derive"] }
# serde_json = "1.0.149"
# serde_yaml = "0.9.34"
# toml = "0.9.11"

[build-dependencies]
iocore = { version = "3.1.0", features = ["walk-glob"] }

#[dev-dependencies]
#assert_cmd = "2.2.0"
#assert_fs = "1.1.3"
#benchmarking = "0.4.13"
#dir-diff = "0.3.3"
#k9 = "0.12.0"
#rstest = { version = "0.26.1" }
#trycmd = "1.2.0"
