StandardOutput=append:/var/log/jellyfin-service.stdout.log
StandardError=append:/var/log/jellyfin-service.stderr.log

# Log Target (LogTarget)
# LogTarget=console
# LogTarget=kmsg
# LogTarget=journal
# LogTarget=syslog
LogTarget=console

# Log Location (LogLocation)
LogLocation=yes # include line and column numbers in log messages

# Log Level (LogLevel)
# LogLevel=debug
# LogLevel=info
# LogLevel=notice
# LogLevel=warning
# LogLevel=err
# LogLevel=crit
# LogLevel=alert
# LogLevel=emerg
LogLevel=debug
