arcane-magic
commit
remotes
status-print-path-if
dir
autocommit-untracked-unstaged.el
q-broken-i-e-wip
untracked
autocommit-untracked-unstaged
path
show-config
ignore
branch-format-the-struggle-aint-virtual
modified
offline
g
add-and-commit-unfolded
diff-head
status
list-branches
log-shash-date-subject
files-changed-since
filenames-diff-list
linux-remote
files-changed-since.emacs-auto-save-2025-10-13-190841-UTC+0000
autocommit-plumbing
qc
st
common-ancestor-to-ref
remotes.el
info
actual-file-dates-commit
q
import-new-files-from-remote-reference
status-porcelain.gawk
onesum
br
status-porcelain.gawk.el
commit-unstaged-and-untracked
